### ISSUE TITLE
Base Request Handler Class

### ISSUE THREAD

**Issue by pab15** [HSU-F20-CS346/MilitantChickens-TP#11]
This Base Request Handler Class implements the following:
Attributes:
- Request Packet Size
- Request Packet Data
- Request Packet
Methods:
- Get/Set Methods For Each Attribute
- GetPacket() -> read packet size, read packet data, build packet, calls HandleRequest()
- HandleRequest() ->reads packet request type, calls either GetRequestHandler() or PostRequestHandler()
- GetRequestHandler()
- PostRequestHandler()

**Comment by abbottjord94** [comment]
This issue may be redundant, as HandleRequest methods were added directly to the GetRequestHeader and PostRequestHeader classes separately in PR #42 .
