### ISSUE TITLE
Post Request Handler Method

### ISSUE THREAD

**Issue by pab15** [HSU-F20-CS346/MilitantChickens-TP#12]
Works As Described Below:
1) Check File System For File Path:
a. If Path Does Not Exist, Send Response With DNE Error
2) Check If File Already Exists, Look At Server Settings To Decide How To Handle, Send Response Packet Based On Decision
3) If File Can Be Placed, Write The File, Send Response Success Packet

**Comment by abbottjord94** [comment]
Partially handled in #42 

Server settings will still need to be implemented. Currently the server will fail to handle POST requests if the file already exists at the specified path.

I'll open a new issue for handling server settings and changing this behavior accordingly.
