### ISSUE TITLE
Write Unit Tests For Server

### ISSUE THREAD

**Issue by abbottjord94** [HSU-F20-CS346/MilitantChickens-TP#14]
Write the following unit tests:
- Establish a connection
- Sending a response of each type
- Handling a request of each type
- Handling failures
- Sending/Receiving files

**Comment by phtcon** [comment]
Thanks for assigning me to this issue.   Respectfully, I must decline.   🤣

But good luck with your project!

**Comment by abbottjord94** [comment]
Hi,

Sorry about that, I was assigning my group members to those issues and I
clicked on yours by mistake. I've removed you from the other issues as well.

Thank you!
